env subst

diff --git a/root/etc/services.d/domain-start/run b/root/etc/services.d/domain-start/run
--- a/root/etc/services.d/domain-start/run
+++ b/root/etc/services.d/domain-start/run
@@ -21,8 +21,8 @@ then
   done
 else
   hr
-  >&2 echo WARNING -- VM Not Found
-  >&2 echo Build VM using "$IMAGE_NAME new"
+  >&2 printf '%s\n' WARNING -- VM Not Found
+  >&2 printf '%s\n' Build VM using "$IMAGE_NAME new"
   hr
   sleep infinity
 fi
